# prometheus.yml
global:
  scrape_interval: 5s
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'afbb-monitor'


scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

