[[section-introduction-and-goals]]
==	Einführung und Ziele

[role="arc42help"]
****
Die westenlichen Anforderungen zur Umsetzung des Projektes sind:

* Zerlegung der Aufgabe in Teilaufgaben
* Zeitplanung für die Projektumsetzung
* Wissenserweiterung
* komplexe Systeme verstehen und konfigurieren
* Nachvollziehbarkeit durch Erstellung einer Architekturdokumentation
* Zuverlässigkeit
* Erstellung eines Prototypens
****

=== Aufgabenstellung

[role="arc42help"]
****
In einem einwöchigen Praktikum besteht die Aufgabe darin, in Teamarbeit eine komplexe, 
informationstechnische Aufgabenstellung zu analysieren, Lösungskonzepte zu entwickeln, diese zu dokumentieren und prototypisch umzusetzen. 
Dabei sollen die notwendigen Teilaufgaben eigenständig identifiziert werden und über mehrere Entwicklungsgruppen verteilt und 
koordiniert werden. In diesem Praktikum sollen grundlegende Konzepte und Architekturmerkmale des Internet of Things benannt und
deren Bedeutung für die Entwicklung eines komplexen IT-Systems dargestellt werden. 
Hierfür sollen verbreitete Technologien und Projekte für ein einfaches IoT-System ausgewählt werden.
Dafür sollen Schnittstellen zwischen Systemkomponeten entworfen und umgesetzt werden.
****

=== Qualitätsziele

[role="arc42help"]
****
.Inhalt
Die Qualitätsziele für das einwöhige Praktikum lauten wie folgt:

* Motivation der Teammitglieder
* Qualifikationen der Projektleitung
* Teamprozesse und Konflikte
* Dokumentation
* Image des Projekts 
* fehlende Ressourcen

****
