[[section-system-scope-and-context]]
== Kontextabgrenzung

[role="arc42help"]
****
.Inhalt
Die Kontextabgrenzung grenzt das System von allen Kommunikationsbeziehungen (Nachbarsystemen und Benutzerrollen) ab.
Sie legt damit die externen Schnittstellen fest.

Differenzieren Sie fachliche (fachliche Ein- und Ausgaben) und technische Kontexte (Kanäle, Protokolle, Hardware), falls nötig.

.Motivation
Die fachlichen und technischen Schnittstellen zur Kommunikation gehören zu den kritischsten Aspekten eines Systems.
Stellen Sie sicher, dass Sie diese komplett verstanden haben.

.Form
Verschiedene Optionen:

* Diverse Kontextdiagramme
* Listen von Kommunikationsbeziehungen mit deren Schnittstellen
****

=== Fachlicher Kontext

[role="arc42help"]
****
.Inhalt
Festlegung *aller* Kommunikationsbeziehungen (Nutzer, IT-Systeme, ...) mit Erklärung der fachlichen Ein- und Ausgabedaten oder Schnittstellen.
Zusätzlich (bei Bedarf) fachliche Datenformate oder Protokolle der Kommunikation mit den Nachbarsystemen.

.Motivation
Alle Beteiligten müssen verstehen, welche fachlichen Informationen mit der Umwelt ausgetauscht werden.

.Form
Alle Diagrammarten, die das System als Blackbox darstellen und die fachlichen Schnittstellen zu den Nachbarsystemen beschreiben.

Alternativ oder ergänzend können Sie eine Tabelle verwenden.
Der Titel gibt den Namen Ihres Systems wieder; die drei Spalten sind: Kommunikationsbeziehung, Eingabe, Ausgabe.
****

[plantuml, generated/plantuml_examplecomponents, svg]
....
scale 800 width
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
 
node "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
} 

cloud {
  [Example 1]
}


database "MySql" {
  folder "This is my folder" {
	[Folder 3]
  }
  frame "Foo" {
	[Frame 4]
  }
}


[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]
[Folder 3] --> [Frame 4]

....

**<Diagramm und/oder Tabelle>**
.Kommunikationswege
[options="header,footer"]
|=============================================================
|Sender|Aktion|Protokoll\Datenformat|Empfanger
|Nutzer|dreht Tangible|Umwelteinfluss|Accelerometer
|Accelerometer|sendet Messwerte|I²C\INT|Wifi Modul
|Thermometer|sendet Messwerte|I²C\FLOAT|Wifi Modul
|Wifi Modul|sendet Messwerte|MQTT\INT&FLOAT|Mosquitto
|Mosquitto|sendet Messwerte|MQTT\INT&FLOAT|Control Center
|Control Center|sendet LED-State|MQTT\INT|Mosquitto
|Mosquitto|sendet LED-State|MQTT\INT|NodeRed
|Mosquitto|sendet LED-State|MQTT\INT|Wifi Modul
|Wifi Modul|sendet LED-State|TCP\INT|LED
|=============================================================
**<optional: Erläuterung der externen fachlichen Schnittstellen>**

=== Technischer Kontext

[role="arc42help"]
****
.Inhalt
Technische Schnittstellen (Kanäle, Übertragungsmedien) zwischen dem System und seiner Umwelt.
Zusätzlich eine Erklärung (_mapping_), welche fachlichen Ein- und Ausgaben über welche technischen Kanäle fließen.

.Motivation
Viele Stakeholder treffen Architekturentscheidungen auf Basis der technischen Schnittstellen des Systems zu seinem Kontext.

Insbesondere bei der Entwicklung von Infrastruktur oder Hardware sind diese technischen Schnittstellen durchaus entscheidend.

.Form
Beispielsweise UML Deployment-Diagramme mit den Kanälen zu Nachbarsystemen, begleitet von einer Tabelle, die Kanäle auf Ein-/Ausgaben abbildet.
****

**<Diagramm oder Tabelle>**

.Schnittstellendefinition - MQTT-Kanäle
[options="header,footer"]
|=============================================================
|Sender|Schnittstelle|gesendete Daten|Typ
|Client|devices/ID/temperature|Temperatur|Float
|Client|devices/ID/direction|Orientierungsdaten|INT
|Server|devices/ID/state|Zustandsdaten|INT
|=============================================================



.Direction - mögliche Zustände
[options="header,footer"]
|=============================================================
|Nr.|Zustand
|0|aufrecht stehend
|1|auf den Kopf stehend
|2|auf der Seite liegend
|=============================================================

.State - mögliche Zustände
[options="header,footer"]
|=============================================================
|Nr.|Zustand|Bedingung|Priorität
|0|verfügbar - grün|Direction: 0|low
|1|beschäftigt - orange|Direction: 1|low
|2|pausierend - blau|Direction: 2|low
|3|Warnung - weiß blinkend|State: 4 an anderem Tangible|high
|4|Kowalski-Alarm - violett blinkend|Temperaturabfall 2°C in 60s|highest
|=============================================================

**<optional: Erläuterung der externen technischen Schnittstellen>**

**<Mapping fachliche auf technische Schnittstellen>**
